<?xml version="1.0" encoding="UTF-8"?>
<!--
  Questo WSDL rappresenta l'interfaccia esposta dal Nodo dei Pagamenti Telematici
  per la verifica dei pagamenti in attesa verso i PSP.
-->
<wsdl:definitions 
	xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata" 
	xmlns:ppt="http://ws.pagamenti.telematici.gov/" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:tns="http://PuntoAccessoPSP.spcoop.gov.it/servizi/RichiestaAvvisi" 
	xmlns:nodo="http://www.agid.gov.it/schemas/pagoPa/nodo" 
	targetNamespace="http://PuntoAccessoPSP.spcoop.gov.it/servizi/RichiestaAvvisi">
	
	<wsdl:types>
		<xsd:schema>
			<xsd:import namespace="http://www.agid.gov.it/schemas/pagoPa/nodo" schemaLocation="../xsd/NodoPerPspSpontaneo.xsd"></xsd:import>
		
			
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="nodoChiediNumeroAvviso">
		<wsdl:part name="bodyrichiesta" element="nodo:nodoChiediNumeroAvviso" />
	</wsdl:message>
	
	<wsdl:message name="nodoChiediNumeroAvvisoResponse">
		<wsdl:part name="bodyrisposta" element="nodo:nodoChiediNumeroAvvisoRisposta" />
	</wsdl:message>
	
	<wsdl:message name="nodoChiediCatalogoServizi">
		<wsdl:part name="bodyrichiesta" element="nodo:nodoChiediCatalogoServizi" />
	</wsdl:message>
	
	<wsdl:message name="nodoChiediCatalogoServiziResponse">
		<wsdl:part name="bodyrisposta" element="nodo:nodoChiediCatalogoServiziRisposta" />
	</wsdl:message>
	
	<wsdl:portType name="RichiestaAvvisi">
		<wsdl:operation name="nodoChiediNumeroAvviso">
			<wsdl:input message="tns:nodoChiediNumeroAvviso" wsam:Action="http://ws.pagamenti.telematici.gov/PPT/nodoChiediNumeroAvvisoRichiesta" />
			<wsdl:output message="tns:nodoChiediNumeroAvvisoResponse" wsam:Action="http://ws.pagamenti.telematici.gov/PPT/nodoChiediNumeroAvvisoRisposta" />
		</wsdl:operation>
		<wsdl:operation name="nodoChiediCatalogoServizi">
			<wsdl:input message="tns:nodoChiediCatalogoServizi" wsam:Action="http://ws.pagamenti.telematici.gov/PPT/nodoChiediCatalogoServiziRichiesta" />
			<wsdl:output message="tns:nodoChiediCatalogoServiziResponse" wsam:Action="http://ws.pagamenti.telematici.gov/PPT/nodoChiediCatalogoServiziRisposta" />
		</wsdl:operation>
	</wsdl:portType>
	
	<wsdl:binding name="RichiestaAvvisibinding" type="tns:RichiestaAvvisi">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="nodoChiediNumeroAvviso">
			<soap:operation soapAction="nodoChiediNumeroAvviso" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
		<wsdl:operation name="nodoChiediCatalogoServizi">
			<soap:operation soapAction="nodoChiediCatalogoServizi" />
			<wsdl:input>
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" />
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	
	<wsdl:service name="RichiestaAvvisiservice">
		<wsdl:port name="PPTPort" binding="tns:RichiestaAvvisibinding">
			<soap:address location="http://PuntoAccessoPSP.spcoop.gov.it/" />
		</wsdl:port>
	</wsdl:service>
	
</wsdl:definitions>
