@startuml
autonumber 
participant ec  as "EC"
participant nodo as "pagoPA"

alt
nodo -> ec : req paaSendRT
ec -[#blue]-> nodo : resp OK
else 
nodo -> ec : req paaSendReceipt
ec -[#blue]-> nodo : resp OK
end


@enduml