@startuml
autonumber

participant pagopa as "pagoPA"
participant ec as "EC"


pagopa -> ec : paaAttivaRPT 
ec -[#blue]-> pagopa : resp OK ( importo, IBAN )
...

ec -> pagopa : nodoInviaRPT 
pagopa -[#blue]-> ec : resp OK

@enduml