@startuml outcomeOKTimeout
title Timeout su outcome positivo

participant pagoPA
participant PSP

== Activate ==

PSP -> pagoPA: activatePaymentNotice req
activate pagoPA
pagoPA -> pagoPA: Generazione token (<color blue>token</color>)
pagoPA --> PSP: activatePaymentNotice res (<color blue>token</color>)
deactivate pagoPA

== Outcome timeout ==

PSP ->x pagoPA: sendPaymentOutcome req (<color blue>token</color>, outcome=<color blue>OK</color>)
note right: In caso di mancata risposta \n il PSP deve avviare un processo di retry

loop retry
    PSP ->x pagoPA: sendPaymentOutcome req (<color blue>token</color>, outcome=<color blue>OK</color>)
end

== Outcome ==

alt token valido
    PSP -> pagoPA: sendPaymentOutcome req (<color blue>token</color>, outcome=<color blue>OK</color>)
    activate pagoPA
    pagoPA --> PSP: sendPaymentOutcome res (<color green>OK</color>)
    deactivate pagoPA
    note right: -La conferma del pagamento avviene\n prima della scadenza del token\n-L'OK conferma al PSP che il pagamento\n non potrà subire variazioni
else token scaduto
    PSP -> pagoPA: sendPaymentOutcome req (<color blue>token</color>, outcome=<color blue>OK</color>)
    activate pagoPA    
    pagoPA --> PSP: sendPaymentOutcome res (<color green>PPT_TOKEN_SCADUTO</color>)
    deactivate pagoPA
    note right: -La conferma del pagamento avviene\n dopo la scadenza del token\n-La piattaforma pagoPA avvierà un processo di retry
else doppio pagamento
    PSP -> pagoPA: sendPaymentOutcome req (<color blue>token</color>, outcome=<color blue>OK</color>)
    activate pagoPA    
    pagoPA --> PSP: sendPaymentOutcome res (<color red>PPT_PAGAMENTO_DUPLICATO</color>)
    deactivate pagoPA
    note right: -La conferma del pagamento avviene\n dopo la scadenza del token
end


@enduml
