@startuml
hide footbox
autonumber 

participant nodo as "pagoPA"
participant psp as "PSP"
participant pg as "Payment Gateway"

pagopa -> pagopa : Start Payment 
pagopA <-> pg : execue transaction
...

nodo -> psp : req pspNotifyPayment ()
psp -[#blue]-> nodo : resp OK

pagopa -> pagopa : Close Payment

psp -> nodo : req  pspSendPaymentOutcome()
nodo -[#blue]-> psp : resp OK
@enduml