@startuml
hide footbox
autonumber

participant nodo as "pagoPA"
participant psp as "PSP"
participant pg as "Payment Gateway"

nodo -> nodo : Start Payment
nodo <-> pg : execute transaction
...

nodo -> psp : req pspNotifyPayment ()
psp -[#blue]-> nodo : resp OK

nodo -> nodo : Close Payment

psp -> nodo : req sendPaymentOutcome()
nodo -[#blue]-> psp : resp OK
@enduml