autonumber 


participant user as "Utilizzatore Finale"
participant nodo as "pagoPA"
participant psp  as "PSP - Banca Seller"
participant buyer  as "Buyer Bank"

nodo -> psp : req nodoInviaCarrelloRPT
psp -[#blue]->: resp OK


user -[#green]-> psp : redirect to PSP Service Url
psp -[#green]-> buyer : redirect to Buyer Bank
user -> buyer :  pay
user -[#green]-> psp : re-direct Seller Bank (OK)
user -[#green]-> nodo : re-direct pagoPA (OK)
nodo -> nodo : Result page
psp -> nodo : nodoInviaRT 
nodo -[#blue]-> psp : resp OK