@startuml
hide footbox
autonumber
actor Utente
participant EC
participant NodoSPC
participant PSP
Utente -> EC: Richiede storno di un pagamento
EC->EC: Genera documento RR
EC -> NodoSPC: req nodoInviaRichiestaStorno
NodoSPC->NodoSPC: Valida RR
NodoSPC->PSP:req pspInviaRichiestaStorno
PSP-[#blue]->NodoSPC: resp KO pspInviaRichiestaStorno
note right: CANALE_RR_DUPLICATA\nCANALE_OPER_NON_STORNABILE\nCANALE_RT_SCONOSCIUTA\nCANALE_SEMANTICA
NodoSPC-[#blue]->EC: resp KO nodoInviaRichiestaStorno
note right : propaga errore
EC -> Utente: Esito KO operazione


@enduml