@startuml
hide footbox
autonumber

participant PSP
participant NodoSPC


PSP -> PSP : Generazione XML
PSP -> NodoSPC : req nodoInviaFlussoRendicontazione
NodoSPC -> NodoSPC : Verifica XML rendicontazione 
NodoSPC -[#blue]-> PSP : resp KO nodoInviaFlussoRendicontazione 
note left : PPT_FLUSSO_SCONOSCIUTO\nPPT_SEMANTICA


@enduml