@startuml
hide footbox
autonumber
actor Utilizzatore_Finale
participant PSP
participant NodoSPC
participant EC
Utilizzatore_Finale -> PSP: Richiesta rimborso
PSP -> NodoSPC: nodoInviaRichiestaRevoca
NodoSPC->NodoSPC: Validazione Richiesta Revoca
note right NodoSPC :PPT_SINTASSI_EXTRASDA\nPPT_SINTASSI_XSD\nPPT_RR_DUPLICATA\nPPT_OPER_NON_REVOCABILE\nPPT_SEMANTICA
NodoSPC-[#0000FF]->PSP:resp KO nodoInviaRichiestaRevoca
PSP-[#0000FF]->Utilizzatore_Finale: Esito KO

@enduml