@startuml
hide footbox
autonumber
participant Cittadino as "Utilizzatore Finale"
participant PSP
participant NodoSPC
participant EC

hnote over NodoSPC : PD in Attesa

Cittadino [#000000]-> PSP: Presenta l'avviso

PSP -> PSP: Elabora dati avviso 


PSP -> NodoSPC: req nodoAttivaRPT
NodoSPC -> NodoSPC : controllo attivaRPT

NodoSPC -> EC : req paaAttivaRPT
EC -> EC : Attiva RPT
EC -[#0000FF]-> NodoSPC : resp OK, paaAttivaRPT

NodoSPC -[#0000FF]-> PSP : resp OK, nodoAttivaRPT

hnote over NodoSPC : RPT Attivata
PSP [#black]-> Cittadino : Presetazione dati Avviso
Cittadino [#black]-> PSP : Autorizza Pagamento
PSP -> PSP : Pagamento
PSP [#black]-> Cittadino: rilascio attestazione
...

EC -> NodoSPC : req nodoInviaRPT
NodoSPC -> NodoSPC : controllo inviaRPT

NodoSPC -[#0000FF]-> EC : resp OK, nodoInviaRPT
hnote over NodoSPC : Pagamento Autorizzato


NodoSPC -> PSP : req pspInviaRPT
PSP -[#0000FF]-> NodoSPC : resp OK, pspInviaRPT


hnote over NodoSPC : RPT Pagata

PSP -> NodoSPC : req nodoInviaRT
NodoSPC -> NodoSPC : controllo inviaRT

hnote over NodoSPC : RT Nodo
NodoSPC -> EC : paaInviaRT
EC -> EC : Modifica Stato Pagamento

EC -[#0000FF]-> NodoSPC : resp OK, paaInviaRT
NodoSPC -[#0000FF]-> PSP : resp OK, nodoInviaRT

hnote over NodoSPC : RT EC

@enduml