@startuml
hide footbox
autonumber
actor Utilizzatore_Finale
participant PSP
participant NodoSPC
participant EC
... passi precedenti non tracciati...
EC->EC:Compone ER
EC -> NodoSPC: nodoInviaRispostaRevoca
NodoSPC->NodoSPC:Valida ER
NodoSPC-[#0000FF]->EC: respo KO nodoInviaRispostaRevoca
note left:PPT_SINTASSI_EXTRAXSD\nPPT_SINTASSI_XSD\nPPT_ER_DUPLICATA\nPPT_RR_SCONOSCIUTA\nPPT_SEMANTICA\nPPT_CANALE_TIMEOUT

@enduml