@startuml
hide footbox
autonumber
actor Utilizzatore_Finale
participant PSP
participant NodoSPC
participant EC
... passi precedenti non tracciati...
EC->EC:Compone ER
EC -> NodoSPC: nodoInviaRispostaRevoca
NodoSPC->NodoSPC:Valida ER
NodoSPC -> PSP: pspInviaRispostaRevoca
PSP-[#0000FF]-->NodoSPC: resp KO pspInviaRispostaRevoca
note left:CANALE_SINTASSI_EXTRAXSD\nCANALE_SINTASSI_XSD\nCANALE_ER_DUPLICATA\nCANALE_RR_SCONOSCIUTA\nCANALE_SEMANTICA
NodoSPC -[#0000FF]->EC: resp KO nodoInviaRispostaRevoca
note left:Propaga Errore

@enduml