@startuml
hide footbox
autonumber 

participant NodoSPC
participant PSP




PSP -> NodoSPC: req nodoInviaRT

   
alt EC non raggiungibile 
NodoSPC -[#blue]-> PSP : resp KO nodoInviaRT
note left NodoSPC : PPT_STAZIONE_INT_PA_IRRAGIUNGIBILE\nPPT_STAZIONE_INT_PA_TIMEOUT

else nessuna risposta timeout
NodoSPC -[#blue]-X PSP 

end


PSP -> NodoSPC : nodoInviaRT
note right PSP : n re-invii RT_PUSH\nad intervallo di tempo crescenti


alt caso OK

NodoSPC -[#blue]-> PSP : resp OK nodoInviaRT

else nessuna risposta o situazione precedente
PSP -> PSP : colloca RT nella lista PULL
NodoSPC -> PSP : pspChiediListaRT
PSP -[#blue]-> NodoSPC : resp OK pspChiediListaRT
NodoSPC -> PSP : pspChiediRT
PSP -[#blue]-> NodoSPC : resp OK pspChiediRT
NodoSPC -> NodoSPC : Valida RT

    alt RT OK
    NodoSPC -> PSP : pspInviaAckRT
    PSP -> PSP : Elimina RT dalla Lista
    PSP -[#blue]-> NodoSPC : resp OK pspInviaAckRT
    else RT KO
    NodoSPC -> PSP : pspInviaAckRT
   
    PSP -[#blue]-> NodoSPC : resp OK pspInviaAckRT
    end
    
end


@enduml