@startuml
hide footbox
autonumber
actor Utilizzatore_Finale
participant PSP
participant NodoSPC
participant EC
Utilizzatore_Finale -> PSP: Richiesta rimborso
PSP -> NodoSPC: nodoInviaRichiestaRevoca
NodoSPC->NodoSPC: Validazione Richiesta Revoca
NodoSPC -> EC: paaInviaRichiestaRevoca
EC-[#blue]->NodoSPC: resp OK paaInviaRichiestaRevoca
NodoSPC -[#blue]-> PSP: resp OK nodoInviaRichiestaRevoca
EC ->EC: Predisposizione ER
EC -> NodoSPC: nodoInviaRispostaRevoca
NodoSPC ->NodoSPC: Validazione ER
NodoSPC -> PSP: pspInviaRispostaRevoca
PSP-[#blue]->NodoSPC: resp OK pspInviaRispostaRevoca
NodoSPC -[#blue]-> EC: resp OK nodoInviaRispostaRevoca
PSP -> Utilizzatore_Finale: Esito


@enduml