@startuml
hide footbox
autonumber

participant PSP
participant NodoSPC
participant EC


...  passi non tracciati ...

EC -> NodoSPC : req nodoChiediElencoFlussiRendicontazione
NodoSPC -> EC : resp KO nodoChiediElencoFlussiRendicontazione
note left NodoSPC : PPT_SINTASSI_EXTRAXSD\nPPT_PSP_SCONOSCIUTO


@enduml