@startuml
hide footbox
autonumber 


participant PSP
participant NodoSPC
participant EC

hnote over NodoSPC : RT presso PSP

PSP -> NodoSPC: req nodoInviaRT
   NodoSPC -> NodoSPC : controllo inviaRT
   
alt

   NodoSPC -[#0000FF]-> PSP : resp KO, nodoInviaRT 
   note right NodoSPC : PPT_RT_DUPLICATA
   PSP -> PSP : Gestione RT Duplicata
   else
   NodoSPC -> NodoSPC : Timeout
   PSP -> PSP : Archivio RT per PULL
end


NodoSPC -> EC : req paaInviaRT

@enduml