@startuml
hide footbox
autonumber
actor Utilizzatore_Finale
participant PSP
participant NodoSPC
participant EC
Utilizzatore_Finale -> PSP: Richiesta rimborso
PSP -> NodoSPC: nodoInviaRichiestaRevoca
NodoSPC->NodoSPC: Validazione Richiesta Revoca
NodoSPC->EC:paaInviaRichiestaRevoca
EC-[#0000FF]->NodoSPC:resp KO paaInviaRichiestaRevoca
note right:PAA_RT_SCONOSCIUTA\nPAA_SINTASSI_XSD\nPAA_SINTASSI_EXTRA_XSD\nPAA_SEMANTICA\nPAA_RR_DUPLICATA\nPAA_OPER_NON_REVOCABILE
NodoSPC-[#0000FF]->PSP:resp KO nodoInviaRichiestaRevoca
note right: PPT_ERRORE_EMESSO_DA_PAA\n(Propaga Errore)
PSP-[#0000FF]->Utilizzatore_Finale: Esito KO

@enduml