@startuml
hide footbox
autonumber
actor Utilizzatore_Finale
participant EC
participant NodoSPC
participant PSP

PSP->PSP: Predisposizione documento ER



alt  Timeout request PSP
PSP -x NodoSPC: req nodoInviaEsitoStorno

else   Timeout EC 
PSP -> NodoSPC: req nodoInviaEsitoStorno
NodoSPC -> NodoSPC : Valida Richiesta

alt Timeout Request EC
NodoSPC -x EC : paaInviaEsitoStorno

else Timeout Response EC
EC -[#blue]-x NodoSPC : resp TO paaInviaEsitoStorno
end

NodoSPC -[#blue]-> PSP : resp KO nodoInviaEsitoStorno



else

PSP -> NodoSPC : resp nodoInviaEsitoStorno
NodoSPC -> NodoSPC : Valida Richiesta 
NodoSPC -> EC : paaInviaEsitoStorno
EC -[#blue]-> NodoSPC : resp paaInviaEsitoStorno
NodoSPC -x PSP : resp TO nodoInviaEsitoStorno
end

EC -> Utilizzatore_Finale: Esito Operazione KO


@enduml